print("Please enter the following information:")
First = input("First name: ")
last = input("Last name: ")
email = input("Email address: ")
phone = input("Phone number: ")
job = input("Job title: ")
ID = input("ID number: ")
Hair = input("Hair Color: ")
Eyes = input("Eye color: ")
Month = input("Which month did you start: ")
Training = input("Have you completed an advanced training?: ")
print()
print("The ID Card is: ")
print("-------------------------------------------------")
print(f"{last.capitalize()},{First.capitalize()}\n{job.title()}\nID: {ID}")
print()
print(f"{email}\n{phone}")
print()
print("Hair: %-15s  Eyes: %s " % (Hair.capitalize(), Eyes.capitalize()))
print("Month: %-15s Training: %s" % (Month.capitalize(), Training.capitalize()))
print("-------------------------------------------------")
